extends Node

signal BUL_create_bulletin
signal BUL_destroy_bulletin

signal INV_try_to_pickup_item
signal INV_ask_update_inventory
signal INV_inventory_updated

signal PLA_freeze_player
signal PLA_unfreeze_player

signal UI_hide_HUD
signal UI_unhide_HUD
